name: Download Postnord data
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 1 * *' # 2AM every 1st of the month
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Fetch the data
      run: python download_postnord.py
    - name: Commit and push
      run: |
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git config --global user.name 'github-actions[bot]'
        git add .
        git commit -m 'Update the data' || echo "Nothing to commit"
        git push
